# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BashGenerator < Formula
  desc "Generate Bash commands by saying what you want"
  homepage "https://github.com/jerilseb/aibash"
  version "1.0.6"
  depends_on :linux

  on_intel do
    if Hardware::CPU.is_64_bit?
      url "https://github.com/jerilseb/aibash/releases/download/v1.0.6/aibash_1.0.6_linux_amd64.tar.gz"
      sha256 "5749ba303ee701f628374aa4985c5a8d644430b0d21fe9c6065e3af555c55fbc"

      def install
        bin.install "aibash"
      end
    end
  end
end
