# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BashGenerator < Formula
  desc "Generate Bash commands by saying what you want"
  homepage "https://github.com/jerilseb/bash-generator"
  version "1.0.8"
  depends_on :linux

  on_intel do
    if Hardware::CPU.is_64_bit?
      url "https://github.com/jerilseb/bash-generator/releases/download/v1.0.8/bash-generator_1.0.8_linux_amd64.tar.gz"
      sha256 "74c7e118a0dbfeb3e93b4274002cbb4d99bb34f0d1f6e2571a816fc6c1885a6c"

      def install
        bin.install "bash-generator"
      end
    end
  end
end
