# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Grpcmd < Formula
  desc "A simple CLI for testing purposes"
  homepage "https://github.com/jerilseb/my-cli"
  version "1.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jerilseb/my-cli/releases/download/v1.0.2/my-cli_1.0.2_darwin_amd64.tar.gz"
      sha256 "31f7fb8661ad02cb5aa47c6609f7538fb46f4600a9fa2802b096e86653e99f3b"

      def install
        bin.install "mycli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jerilseb/my-cli/releases/download/v1.0.2/my-cli_1.0.2_darwin_arm64.tar.gz"
      sha256 "068a472585bfad0f2fc20cb179815e325574c913cd49b26156892203a3368d30"

      def install
        bin.install "mycli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/jerilseb/my-cli/releases/download/v1.0.2/my-cli_1.0.2_linux_amd64.tar.gz"
      sha256 "1d0f4fcb4bfe4c969e464fa18f4ba80137da5ef49989635fe24c91dab022a366"

      def install
        bin.install "mycli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jerilseb/my-cli/releases/download/v1.0.2/my-cli_1.0.2_linux_arm64.tar.gz"
      sha256 "c1afdb2726047e89f3ab269c51bc7a52db0ec11e4b4b83eb6f274056329c9632"

      def install
        bin.install "mycli"
      end
    end
  end
end
