# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MyCli < Formula
  desc "A simple CLI for testing purposes"
  homepage "https://github.com/jerilseb/my-cli"
  version "1.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jerilseb/my-cli/releases/download/v1.0.3/my-cli_1.0.3_darwin_amd64.tar.gz"
      sha256 "9b5afad865d2d10799827aedab945e93788d1b183386c1d0aa493a79e32e46cf"

      def install
        bin.install "mycli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jerilseb/my-cli/releases/download/v1.0.3/my-cli_1.0.3_darwin_arm64.tar.gz"
      sha256 "5fe02b809ca4fc0293f71e517757d59225ab2eb8716c964e04c3e0194d8f152e"

      def install
        bin.install "mycli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/jerilseb/my-cli/releases/download/v1.0.3/my-cli_1.0.3_linux_amd64.tar.gz"
      sha256 "514cc18022813f8d078ffb1885f4a29cfa2c7bab063b4930cb2055112709549d"

      def install
        bin.install "mycli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jerilseb/my-cli/releases/download/v1.0.3/my-cli_1.0.3_linux_arm64.tar.gz"
      sha256 "29edb7c2adcaa83efa936aafb1d160c13833918cb51c5249d0453e6925918842"

      def install
        bin.install "mycli"
      end
    end
  end
end
