# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spacer < Formula
  desc "A CLI app for cleaning up large files"
  homepage "https://github.com/jerilseb/spacer"
  version "1.0.0"

  on_macos do
    on_intel do
      url "https://github.com/jerilseb/spacer/releases/download/v1.0.0/spacer_1.0.0_darwin_amd64.tar.gz"
      sha256 "0073d7a6b1ec09315382bfb60d0f9a1d2580ca730d3ec84695320e2a569710b4"

      def install
        bin.install "spacer"
      end
    end
    on_arm do
      url "https://github.com/jerilseb/spacer/releases/download/v1.0.0/spacer_1.0.0_darwin_arm64.tar.gz"
      sha256 "238c7a712645b676ee9f07ababa4c32d60205e82ddb77fe6f28db0ca4cef2e5d"

      def install
        bin.install "spacer"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jerilseb/spacer/releases/download/v1.0.0/spacer_1.0.0_linux_amd64.tar.gz"
        sha256 "dac8044f6bbab4c72b572279a5bd59f55811e23c636540f37a3ce06d1862387a"

        def install
          bin.install "spacer"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jerilseb/spacer/releases/download/v1.0.0/spacer_1.0.0_linux_arm64.tar.gz"
        sha256 "9080b7af2ccae6600dfba3c7f9dcabd6d0de7b822125c84c3b3aadbb0074e8a0"

        def install
          bin.install "spacer"
        end
      end
    end
  end
end
